UserServlet
yalukaiwo/step-tinder pull request #11
Opened 2024-03-21 18:58 UTC by MaksymZymyn

2024-03-21 19:02 UTC, sirius91191 approved these changes

2024-03-21 21:08 UTC, yalukaiwo requested changes

2024-03-21 21:08 UTC, yalukaiwo commented on src/main/java/servlets/UserServlet.java
> +    private int currentIndex = 0;
эта штука должна работать так:
делается запрос в базу первого попавшегося юзера, которого пользователь ни лайкал, ни дизлайкал. Твоя реализация слишком тажелая на сервер

2024-03-21 21:08 UTC, yalukaiwo commented on src/main/java/servlets/UserServlet.java
> +    private int currentIndex = 0;
т.е всё через sql

2024-03-22 15:35 UTC, yalukaiwo approved these changes
approved

2024-03-22 15:38 UTC, merged