Users
yalukaiwo/step-tinder pull request #4
Opened 2024-03-15 14:29 UTC by MaksymZymyn

2024-03-15 15:58 UTC, sirius91191 approved these changes

2024-03-15 18:38 UTC, yalukaiwo commented on src/main/java/users/User.java
> +
I don't think it needts to be Serializable anymore

2024-03-15 18:41 UTC, yalukaiwo commented on src/main/java/utils/environment/ConnectionDetails.java
> +public class ConnectionDetails {
this class doesn't have to be public. it is only used inside the package

2024-03-15 18:44 UTC, yalukaiwo requested changes
Users part is on me. The sql files are good. thought some changes will be implemented since i would like to do login by username rather than email. Redo all the Likes-related methods in LikesDAO. Given it is an independent database instance, requests to it should be sent from a separate DAO. No need for procfile yet

2024-03-16 11:33 UTC, yalukaiwo requested changes
Sorry for torturing you with changes. new comments added

2024-03-16 11:33 UTC, yalukaiwo commented on src/main/java/requests.http
unnecessary file

2024-03-16 11:33 UTC, yalukaiwo commented on src/main/java/servlets/ParameterServlet.java
Also an unnecesary file. unused servlet which will not be used.

2024-03-16 11:33 UTC, yalukaiwo commented on src/main/java/servlets/UsersRedirectServlet.java
Unused servlet.

2024-03-16 11:33 UTC, yalukaiwo commented on src/main/resources/db/migration/V0001_create_tables.sql
> +);
table users doesn't have created_at and updated_at

2024-03-16 11:33 UTC, yalukaiwo commented on src/main/resources/db/migration/V0001_create_tables.sql
> +CREATE TABLE chats (
this table is unnecessary

2024-03-16 11:33 UTC, yalukaiwo commented on src/main/resources/templates/auth.ftl
there is login.ftl already which serves the same purpose

2024-03-16 11:33 UTC, yalukaiwo commented on src/main/java/likes/LikesDAO.java
> +    private Like createLikeFromResultSet(ResultSet resultSet) throws SQLException {
fromResultSet in my opinion should be a static function in Like.java. Look at User.java fromRS function for reference

2024-03-16 11:33 UTC, yalukaiwo commented on src/main/java/likes/Like.java
> +    private final int user_to;
user_from and user_to are UUID, not int

2024-03-16 11:33 UTC, yalukaiwo commented on src/main/java/database/DatabaseSetup.java
unnesessary file for now

2024-03-16 11:36 UTC, sirius91191 approved these changes

2024-03-16 11:37 UTC, sirius91191 approved these changes

2024-03-16 11:38 UTC, sirius91191 approved these changes

2024-03-16 16:36 UTC, sirius91191 approved these changes

2024-03-16 17:45 UTC, yalukaiwo requested changes

2024-03-16 17:45 UTC, yalukaiwo commented on src/main/java/likes/LikeDAO.java
> +             String sql = "DELETE FROM likes WHERE userId = ?";
user_from

2024-03-16 17:45 UTC, yalukaiwo commented on src/main/java/likes/LikeService.java
> +    public boolean hasBeenLiked(UUID id, String user_to) {
UUID user_to

2024-03-16 17:45 UTC, yalukaiwo commented on src/main/resources/db/migration/V002__initial_data.sql
> +CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
remove uuid-ossp

2024-03-16 17:45 UTC, yalukaiwo commented on src/main/resources/db/migration/V002__initial_data.sql
> +INSERT INTO users (id, username, full_name, picture, password) VALUES
remove manual id set

2024-03-16 17:45 UTC, yalukaiwo commented on src/main/resources/templates/auth.ftl
remove file

2024-03-16 22:35 UTC, yalukaiwo approved these changes
approved. some minor fixes to be done

2024-03-16 22:35 UTC, yalukaiwo commented on src/main/java/servlets/LikeServlet.java
> +    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
no need to redirect to get on post. either don't create an endpoint or throw 400 error

2024-03-16 22:36 UTC, merged