servlets
yalukaiwo/step-tinder pull request #8
Opened 2024-03-17 21:28 UTC by MaksymZymyn

2024-03-18 13:57 UTC, sirius91191 approved these changes

2024-03-19 06:07 UTC, yalukaiwo requested changes

2024-03-19 06:07 UTC, yalukaiwo commented on src/main/java/App.java
> +        handler.addServlet(new ServletHolder(new StaticFileServlet("static")), "/css/*");
we don't need another endpoint for css, it's included by /static

2024-03-19 06:07 UTC, yalukaiwo commented on src/main/java/likes/Like.java
> +    UUID id;
private final ?

2024-03-19 06:07 UTC, yalukaiwo commented on src/main/java/likes/LikeService.java
> +    LikeDAO likeDAO;
private final ?

2024-03-19 06:07 UTC, yalukaiwo commented on src/main/java/servlets/LikeServlet.java
>      protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
what exactly does this doPost do ?

2024-03-19 06:07 UTC, yalukaiwo commented on src/main/java/servlets/LoginServlet.java
> +    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws IOException {
// i will rewrite this later

2024-03-19 06:07 UTC, yalukaiwo commented on src/main/java/users/User.java
> +    UUID id;
private final ?

2024-03-19 17:58 UTC, yalukaiwo requested changes

2024-03-19 17:58 UTC, yalukaiwo commented on src/main/java/servlets/UserServlet.java
> +    public static ArrayList<User> users = new ArrayList<>();
UserServlet should not contain any static variables. Every time LikeServlet needs a list of users, it should resort to corresponding function in UserService.java. same applies for counter. i don't really get the point of this at the moment anyway.

2024-03-19 20:54 UTC, sirius91191 approved these changes

2024-03-20 12:00 UTC, yalukaiwo approved these changes
approved after changes

2024-03-20 12:17 UTC, merged